[versions]
compiler = "1.3.2"
compose-bom = "2022.11.00"
accompanist = "0.27.0"

[libraries]
activity = "androidx.activity:activity-compose:1.6.1"
bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
foundation = { module = "androidx.compose.foundation:foundation" }
animation = { module = "androidx.compose.animation:animation" }
animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-util = { module = "androidx.compose.ui:ui-util" }

material3-core = { module = "androidx.compose.material3:material3" }
material3-adapter = "com.google.android.material:compose-theme-adapter-3:1.0.21"
material-icons = { module = "androidx.compose.material:material-icons-extended" }

# Here until M3's swipeable became public https://issuetracker.google.com/issues/234640556
material-core = { module = "androidx.compose.material:material" }

accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
