[versions]
compiler = "1.3.2"
compose = "1.2.1"
accompanist = "0.25.1"
material3 = "1.0.0-rc01"

[libraries]
activity = "androidx.activity:activity-compose:1.6.0"
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }

material3-core = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
material3-adapter = "com.google.android.material:compose-theme-adapter-3:1.0.20"
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager-core = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
