[versions]
compose = "1.2.0-alpha07"
accompanist = "0.24.6-alpha"

[libraries]
activity = "androidx.activity:activity-compose:1.6.0-alpha01"
foundation = { module = "androidx.compose.foundation:foundation", version.ref="compose" }
animation = { module = "androidx.compose.animation:animation", version.ref="compose" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref="compose" }

material3-core = "androidx.compose.material3:material3:1.0.0-alpha09"
material3-adapter = "com.google.android.material:compose-theme-adapter-3:1.0.6"
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref="compose" }

accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref="accompanist" }