blank_issues_enabled: false
contact_links:
  - name: üñ•Ô∏è Mihon website
    url: https://mihon.app/
    about: Guides, troubleshooting, and answers to common questions
  - name: ‚ùå Help with Extensions
    url: https://mihon.app/docs/faq/browse/extensions
    about: For extension-related questions/issues
