blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Extension/source issue
    url: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose
    about: Issues and requests for extensions and sources should be opened here.
  - name: ğŸ“¦ Tachiyomi extensions
    url: https://github.com/tachiyomiorg/tachiyomi-extensions
    about: Extensions and sources.
  - name: ğŸŒ Tachiyomi website
    url: https://tachiyomi.org/help/
    about: Guides, troubleshooting, and answers to common questions.
