name: Issue closer
on:
  issues:
    types: [opened, edited, reopened]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Autoclose issues
        uses: arkon/issue-closer-action@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          rules: |
            [
              {
                "type": "body",
                "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
                "message": "The acknowledgment section was not removed."
              },
              {
                "type": "body",
                "regex": ".*\\* (Tachiyomi version|Android version|Device): \\?.*",
                "message": "Requested information in the template was not filled out."
              },
              {
                "type": "both",
                "regex": ".*(aniyomi|anime).*",
                "ignoreCase": true,
                "message": "Tachiyomi does not support anime, and has no plans to support anime. In addition Tachiyomi is not affiliated with Aniyomi https://github.com/jmir1/aniyomi"
              }
            ]
